const allCards = [
    // ==================================================================
    // === KHORINIS
    // ==================================================================
    { id: "Motloch_1", name: "Motłoch", type: "Unit", power: 1, faction: "Khorinis", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "motloch" },
    { id: "Motloch_2", name: "Motłoch", type: "Unit", power: 1, faction: "Khorinis", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "motloch" },
    { id: "Motloch_3", name: "Motłoch", type: "Unit", power: 1, faction: "Khorinis", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "motloch" },
    { id: "Kardiff", name: "Kardiff", type: "Unit", power: 1, faction: "Khorinis", row: "siege", abilities: ["spy"], isHero: false },
    { id: "Girion", name: "Girion", type: "Unit", power: 1, faction: "Khorinis", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Albrecht", name: "Albrecht", type: "Unit", power: 1, faction: "Khorinis", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Ingmar", name: "Ingmar", type: "Unit", power: 1, faction: "Khorinis", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Valentino", name: "Valentino", type: "Unit", power: 1, faction: "Khorinis", row: "melee", isHero: false },
    { id: "Alrik", name: "Alrik", type: "Unit", power: 2, faction: "Khorinis", row: "melee", isHero: false },
    { id: "Mika", name: "Mika", type: "Unit", power: 2, faction: "Khorinis", row: "melee", isHero: false },
    { id: "Bartok", name: "Bartok", type: "Unit", power: 4, faction: "Khorinis", row: "ranged", isHero: false },
    { id: "Straznik_miejski_1", name: "Strażnik miejski", type: "Unit", power: 4, faction: "Khorinis", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Straznik_miejski" },
    { id: "Straznik_miejski_2", name: "Strażnik miejski", type: "Unit", power: 4, faction: "Khorinis", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Straznik_miejski" },
    { id: "Straznik_miejski_3", name: "Strażnik miejski", type: "Unit", power: 4, faction: "Khorinis", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Straznik_miejski" },
    { id: "Wambo", name: "Wambo", type: "Unit", power: 4, faction: "Khorinis", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Bosper", name: "Bosper", type: "Unit", power: 4, faction: "Khorinis", row: "ranged", isHero: false },
    { id: "Keroloth", name: "Keroloth", type: "Unit", power: 5, faction: "Khorinis", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "KerolothSengrathTandor" },
    { id: "Sengrath", name: "Sengrath", type: "Unit", power: 5, faction: "Khorinis", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "KerolothSengrathTandor" },
    { id: "Tandor", name: "Tandor", type: "Unit", power: 5, faction: "Khorinis", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "KerolothSengrathTandor" },
    { id: "Gerold", name: "Gerold", type: "Unit", power: 5, faction: "Khorinis", row: "ranged", isHero: false },
    { id: "Pablo", name: "Pablo", type: "Unit", power: 5, faction: "Khorinis", row: "melee", isHero: false },
    { id: "Constantino", name: "Constantino", type: "Unit", power: 5, faction: "Khorinis", row: "siege", abilities: ["medic"], isHero: false },
    { id: "Martin", name: "Martin", type: "Unit", power: 5, faction: "Khorinis", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Ruga", name: "Ruga", type: "Unit", power: 5, faction: "Khorinis", row: "renged", isHero: false },
    { id: "Wulfgar", name: "Wulfgar", type: "Unit", power: 5, faction: "Khorinis", row: "melee", isHero: false },
    { id: "Orik", name: "Orik", type: "Unit", power: 6, faction: "Khorinis", row: "siege", isHero: false },
    { id: "Esmeralda", name: "Esmeralda", type: "Unit", power: 6, faction: "Khorinis", row: "siege", isHero: false },
    { id: "Rycerz_1", name: "Rycerz", type: "Unit", power: 6, faction: "Khorinis", row: "siege", isHero: false },
    { id: "Rycerz_2", name: "Rycerz", type: "Unit", power: 6, faction: "Khorinis", row: "siege", isHero: false },
    { id: "Dzialo_1", name: "Działo", type: "Unit", power: 6, faction: "Khorinis", row: "siege", isHero: false },
    { id: "Dzialo_2", name: "Działo", type: "Unit", power: 6, faction: "Khorinis", row: "siege", isHero: false },
    { id: "Udar", name: "Udar", type: "Unit", power: 6, faction: "Khorinis", row: "ranged", isHero: false },
    { id: "Paladyn_1", name: "Paladyn", type: "Unit", power: 8, faction: "Khorinis", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "Paladyn" },
    { id: "Paladyn_2", name: "Paladyn", type: "Unit", power: 8, faction: "Khorinis", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "Paladyn" },
    { id: "Lord_Andre", name: "Lord Andre", type: "Unit", power: 10, faction: "Khorinis", row: "melee", isHero: true },
    { id: "Lord_Hagen", name: "Lord Hagen", type: "Unit", power: 10, faction: "Khorinis", row: "melee", isHero: true },
    { id: "Garond", name: "Kapitan Garond", type: "Unit", power: 10, faction: "Khorinis", row: "melee", isHero: true },
    { id: "Lothar", name: "Lothar", type: "Unit", power: 10, faction: "Khorinis", row: "ranged", isHero: true },
    { id: "Swiety_plomien", name: "Święty płomień", type: "Leader", faction: "Khorinis", abilities: ['leader_clear_weather'] },
    { id: "Nie_boje_sie,_gdy_ciemno_jest", name: "Nie boję się, gdy ciemno jest", type: "Leader", faction: "Khorinis", abilities: ['leader_play_fog'] },
    { id: "Innos_Pan_Ognia", name: "Innos Pan Ognia", type: "Leader", faction: "Khorinis", abilities: ['leader_scorch_ranged'] },
    { id: "Oko_Innosa", name: "Oko Innosa", type: "Leader", faction: "Khorinis", abilities: ['leader_siege_boost'] },
    { id: "Zastepy_Innosa", name: "Zastępy Innosa", type: "Leader", faction: "Khorinis", abilities: ['leader_scorch_siege'] },
    { id: "Bilgot", name: "Bilgot", type: "Unit", power: 0, faction: "Khorinis", row: "melee", isHero: false, isToken: true },
    { id: "Abuyn", name: "Abuyn", type: "Unit", power: 0, faction: "Khorinis", row: "melee", isHero: false, isToken: true },
    { id: "Peck", name: "Peck", type: "Unit", power: 0, faction: "Khorinis", row: "melee", isHero: false, isToken: true },

    // ==================================================================
    // === POTWORY
    // ==================================================================
    { id: "Olbrzymi_szczur_1", name: "Olbrzymi szczur", type: "Unit", power: 1, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Olbrzymi_szczur" },
    { id: "Olbrzymi_szczur_2", name: "Olbrzymi szczur", type: "Unit", power: 1, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Olbrzymi_szczur" },
    { id: "Olbrzymi_szczur_3", name: "Olbrzymi szczur", type: "Unit", power: 1, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Olbrzymi_szczur" },
    { id: "Krwiopijca", name: "Krwiopijca", type: "Unit", power: 2, faction: "Potwory", row: "ranged", isHero: false },
    { id: "Dzik", name: "Dzik", type: "Unit", power: 2, faction: "Potwory", row: "ranged", isHero: false },
    { id: "Polna_bestia", name: "Polna bestia", type: "Unit", power: 2, faction: "Potwory", row: "ranged", isHero: false },
    { id: "Bagienny_truten", name: "Bagienny truteń", type: "Unit", power: 2, faction: "Potwory", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Harpia", name: "Harpia", type: "Unit", power: 2, faction: "Potwory", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Bagienny_szczur", name: "Bagienny szczur", type: "Unit", power: 2, faction: "Potwory", row: "ranged", isHero: false },
    { id: "Kretoszczur", name: "Kretoszczur", type: "Unit", power: 2, faction: "Potwory", row: "melee", isHero: false },
    { id: "Scierwojad_1", name: "Ścierwojad", type: "Unit", power: 2, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Scierwojad" },
    { id: "Scierwojad_2", name: "Ścierwojad", type: "Unit", power: 2, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Scierwojad" },
    { id: "Scierwojad_3", name: "Ścierwojad", type: "Unit", power: 2, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Scierwojad" },
    { id: "Czarny_wilk", name: "Czarny wilk", type: "Unit", power: 2, faction: "Potwory", row: "siege", abilities: ["muster"], isHero: false, baseId: "Wilk", musterRole: "master" },
    { id: "Wilk_1", name: "Wilk", type: "Unit", power: 4, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Wilk", musterRole: "slug" },
    { id: "Wilk_2", name: "Wilk", type: "Unit", power: 4, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Wilk", musterRole: "slug" },
    { id: "Wilk_3", name: "Wilk", type: "Unit", power: 4, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Wilk", musterRole: "slug" },
    { id: "Pelzacz", name: "Pełzacz", type: "Unit", power: 4, faction: "Potwory", row: "melee", isHero: false },
    { id: "Goblin_1", name: "Goblin", type: "Unit", power: 4, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Goblin" },
    { id: "Goblin_2", name: "Goblin", type: "Unit", power: 4, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Goblin" },
    { id: "Goblin_3", name: "Goblin", type: "Unit", power: 4, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Goblin" },
    { id: "Czarny_goblin", name: "Czarny goblin", type: "Unit", power: 4, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Goblin" },
    { id: "Goblin_wojownik", name: "Goblin wojownik", type: "Unit", power: 5, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Goblin" },
    { id: "Waz_blotny", name: "Wąż błotny", type: "Unit", power: 5, faction: "Potwory", row: "ranged", isHero: false },
    { id: "Pelzacz_wojownik", name: "Pełzacz wojownik", type: "Unit", power: 5, faction: "Potwory", row: "melee", isHero: false },
    { id: "Lodowy_wilk", name: "Lodowy wilk", type: "Unit", power: 5, faction: "Potwory", row: "melee", isHero: false },
    { id: "Topielec", name: "Topielec", type: "Unit", power: 5, faction: "Potwory", row: "melee", isHero: false },
    { id: "Jaszczur", name: "Jaszczur", type: "Unit", power: 5, faction: "Potwory", row: "melee", isHero: false },
    { id: "Brzytwiak", name: "Brzytwiak", type: "Unit", power: 5, faction: "Potwory", row: "melee", isHero: false },
    { id: "Zebacz_1", name: "Zębacz", type: "Unit", power: 6, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Zebacz" },
    { id: "Zebacz_2", name: "Zębacz", type: "Unit", power: 6, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Zebacz" },
    { id: "Zebacz_3", name: "Zębacz", type: "Unit", power: 6, faction: "Potwory", row: "melee", abilities: ["muster"], isHero: false, baseId: "Zebacz" },
    { id: "Troll", name: "Troll", type: "Unit", power: 6, faction: "Potwory", row: "siege", isHero: false },
    { id: "Troll_jaskiniowy", name: "Troll jaskiniowy", type: "Unit", power: 6, faction: "Potwory", row: "siege", isHero: false },
    { id: "Smoczy_zebacz", name: "Smoczy zębacz", type: "Unit", power: 6, faction: "Potwory", row: "melee", isHero: false },
    { id: "Ognisty_jaszczur", name: "Ognisty jaszczur", type: "Unit", power: 7, faction: "Potwory", row: "ranged", abilities: ["scorch_row"], isHero: false },
    { id: "Sniacy", name: "Śniący", type: "Unit", power: 8, faction: "Potwory", row: ["melee", "ranged"], abilities: ["agile", "morale_boost"], isHero: true },
    { id: "Cieniostwor", name: "Cieniostwór", type: "Unit", power: 9, faction: "Potwory", row: "siege", isHero: false },
    { id: "Krolowa_pelzaczy", name: "Królowa pełzaczy", type: "Unit", power: 10, faction: "Potwory", row: "ranged", isHero: true },
    { id: "Czarny_troll", name: "Czarny troll", type: "Unit", power: 10, faction: "Potwory", row: "melee", isHero: true },
    { id: "Feomathar", name: "Feomathar", type: "Unit", power: 10, faction: "Potwory", row: "melee", isHero: true },
    { id: "Drzewa_maja_uszy", name: "Drzewa mają uszy", type: "Leader", faction: "Potwory", isHero: false, abilities: ['leader_spy_boost'] },
    { id: "Selekcja_naturalna", name: "Selekcja naturalna", type: "Leader", faction: "Potwory", isHero: false, abilities: ['leader_simulate_use'] },
    { id: "Instynkt_stadny", name: "Instynkt stadny", type: "Leader", faction: "Potwory", isHero: false, abilities: ['leader_draw_from_graveyard'] },
    { id: "Zew_puszczy", name: "Zew puszczy", type: "Leader", faction: "Potwory", isHero: false, abilities: ['leader_play_any_weather'] },
    { id: "Zadza_krwi", name: "Żądza krwi", type: "Leader", faction: "Potwory", isHero: false, abilities: ['leader_melee_boost'] },
    { id: "Preriowy_scierwojad", name: "Preriowy ścierwojad", type: "Unit", power: 0, faction: "Potwory", row: "melee", isHero: false, isToken: true },
    { id: "Jaszczuroczlek", name: "Jaszczuroczłek", type: "Unit", power: 0, faction: "Potwory", row: "melee", isHero: false, isToken: true },
    { id: "Topielec_spod_tamy", name: "Topielec spod tamy", type: "Unit", power: 0, faction: "Potwory", row: "melee", isHero: false, isToken: true },
    { id: "Finkregh", name: "Finkregh", type: "Unit", power: 0, faction: "Potwory", row: "melee", isHero: false, isToken: true },
    { id: "Pandrodor", name: "Pandrodor", type: "Unit", power: 0, faction: "Potwory", row: "melee", isHero: false, isToken: true },
    { id: "Feodaron", name: "Feodaron", type: "Unit", power: 0, faction: "Potwory", row: "melee", isHero: false, isToken: true },
    { id: "Pedrakhan", name: "Pedrakhan", type: "Unit", power: 0, faction: "Potwory", row: "melee", isHero: false, isToken: true },

    // ==================================================================
    // === NAJEMNICY
    // ==================================================================
    { id: "Bennet", name: "Bennet", type: "Unit", power: 0, faction: "Najemnicy", row: "siege", abilities: ["medic"], isHero: false },
    { id: "Sagitta", name: "Sagitta", type: "Unit", power: 1, faction: "Najemnicy", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Thekla", name: "Thekla", type: "Unit", power: 1, faction: "Najemnicy", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Sekob", name: "Sekob", type: "Unit", power: 2, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Zbuntowany_farmer_1", name: "Zbuntowany farmer", type: "Unit", power: 2, faction: "Najemnicy", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Zbuntowany_farmer" },
    { id: "Zbuntowany_farmer_2", name: "Zbuntowany farmer", type: "Unit", power: 2, faction: "Najemnicy", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Zbuntowany_farmer" },
    { id: "Zbuntowany_farmer_3", name: "Zbuntowany farmer", type: "Unit", power: 2, faction: "Najemnicy", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Zbuntowany_farmer" },
    { id: "Dar", name: "Dar", type: "Unit", power: 2, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Bronko", name: "Bronko", type: "Unit", power: 2, faction: "Najemnicy", row: "melee", isHero: false },
    { id: "Rosi", name: "Rosi", type: "Unit", power: 3, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Najemnik_1", name: "Najemnik", type: "Unit", power: 3, faction: "Najemnicy", row: "melee", isHero: false, baseId: "Najemnik" },
    { id: "Najemnik_2", name: "Najemnik", type: "Unit", power: 3, faction: "Najemnicy", row: "melee", isHero: false, baseId: "Najemnik" },
    { id: "Najemnik_3", name: "Najemnik", type: "Unit", power: 3, faction: "Najemnicy", row: "melee", isHero: false, baseId: "Najemnik" },
    { id: "Najemnik_4", name: "Najemnik", type: "Unit", power: 3, faction: "Najemnicy", row: "melee", isHero: false, baseId: "Najemnik" },
    { id: "Raoul", name: "Raoul", type: "Unit", power: 3, faction: "Najemnicy", row: "siege", isHero: false },
    { id: "Fester", name: "Fester", type: "Unit", power: 3, faction: "Najemnicy", row: "melee", isHero: false },
    { id: "Wasili", name: "Wasili", type: "Unit", power: 4, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Erol", name: "Erol", type: "Unit", power: 4, faction: "Najemnicy", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Bengar", name: "Bengar", type: "Unit", power: 4, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Rod", name: "Rod", type: "Unit", power: 4, faction: "Najemnicy", row: "melee", isHero: false },
    { id: "Buster", name: "Buster", type: "Unit", power: 5, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Cipher", name: "Cipher", type: "Unit", power: 5, faction: "Najemnicy", row: "siege", isHero: false },
    { id: "Engardo", name: "Engardo", type: "Unit", power: 5, faction: "Najemnicy", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Engardo" },
    { id: "Alvares", name: "Alvares", type: "Unit", power: 5, faction: "Najemnicy", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Engardo" },
    { id: "Khaled", name: "Khaled", type: "Unit", power: 6, faction: "Najemnicy", row: "siege", isHero: false },
    { id: "Patrick", name: "Patrick", type: "Unit", power: 6, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Sentenza", name: "Sentenza", type: "Unit", power: 6, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Bulko", name: "Bulko", type: "Unit", power: 6, faction: "Najemnicy", row: "melee", isHero: false },
    { id: "Jarvis", name: "Jarvis", type: "Unit", power: 7, faction: "Najemnicy", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Wilk", name: "Wilk", type: "Unit", power: 9, faction: "Najemnicy", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Cord", name: "Cord", type: "Unit", power: 10, faction: "Najemnicy", row: "siege", isHero: false },
    { id: "Lowca_smokow_1", name: "Łowca smoków", type: "Unit", power: 10, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Lowca_smokow_2", name: "Łowca smoków", type: "Unit", power: 10, faction: "Najemnicy", row: "ranged", isHero: false },
    { id: "Lee", name: "Lee", type: "Unit", power: 10, faction: "Najemnicy", row: "melee", isHero: true },
    { id: "Onar", name: "Onar", type: "Unit", power: 10, faction: "Najemnicy", row: "melee", abilities: ["medic"], isHero: true },
    { id: "Torlof", name: "Torlof", type: "Unit", power: 10, faction: "Najemnicy", row: "siege", isHero: true },
    { id: "Sylvio", name: "Sylvio", type: "Unit", power: 10, faction: "Najemnicy", row: "ranged", isHero: true },
    { id: "Chlopcy_z_Kolonii", name: "Chłopcy z Kolonii", type: "Leader", faction: "Najemnicy", abilities: ['leader_cancel_opponent_ability'] },
    { id: "Wiesz_jak_czestu_pada_tu_deszcz?", name: "Wiesz jak częstu pada tu deszcz?", type: "Leader", faction: "Najemnicy", abilities: ['leader_play_rain'] },
    { id: "Kuchnia_polowa", name: "Kuchnia polowa", type: "Leader", faction: "Najemnicy", abilities: ['leader_double_medic'] },
    { id: "Wlasciciel_Ziemski", name: "Właściciel Ziemski", type: "Leader", faction: "Najemnicy", abilities: ['leader_draw_from_opponent_graveyard'] },
    { id: "Szybki_zwiad", name: "Szybki zwiad", type: "Leader", faction: "Najemnicy", abilities: ['leader_simulate_use'] },
    { id: "Baloro", name: "Baloro", type: "Unit", power: 0, faction: "Najemnicy", row: "melee", isHero: false, isToken: true },
    { id: "Okyl", name: "Okyl", type: "Unit", power: 0, faction: "Najemnicy", row: "melee", isHero: false, isToken: true },

    // ==================================================================
    // === KLASZTOR
    // ==================================================================
    { id: "Barania_kielbasa_1", name: "Barania kiełbasa", type: "Unit", power: 0, faction: "Klasztor", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Barania_kielbasa_2", name: "Barania kiełbasa", type: "Unit", power: 0, faction: "Klasztor", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Barania_kielbasa_3", name: "Barania kiełbasa", type: "Unit", power: 0, faction: "Klasztor", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Dyrian", name: "Dyrian", type: "Unit", power: 1, faction: "Klasztor", row: "ranged", isHero: false },
    { id: "Igaraz", name: "Igaraz", type: "Unit", power: 2, faction: "Klasztor", row: "ranged", abilities: ["muster"], isHero: false, baseId: "IgarazAgon" },
    { id: "Agon", name: "Agon", type: "Unit", power: 2, faction: "Klasztor", row: "ranged", abilities: ["muster"], isHero: false, baseId: "IgarazAgon" },
    { id: "Ulf", name: "Ulf", type: "Unit", power: 2, faction: "Klasztor", row: "ranged", abilities: ["muster"], isHero: false, baseId: "IgarazAgon" },
    { id: "Garwig", name: "Garwig", type: "Unit", power: 2, faction: "Klasztor", row: "ranged", isHero: false },
    { id: "Babo", name: "Babo", type: "Unit", power: 3, faction: "Klasztor", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Straznik_klasztoru_1", name: "Strażnik klasztoru", type: "Unit", power: 3, faction: "Klasztor", row: "melee", abilities: ["muster"], isHero: false, baseId: "Straznik_klasztoru" },
    { id: "Straznik_klasztoru_2", name: "Strażnik klasztoru", type: "Unit", power: 3, faction: "Klasztor", row: "melee", abilities: ["muster"], isHero: false, baseId: "Straznik_klasztoru" },
    { id: "Straznik_klasztoru_3", name: "Strażnik klasztoru", type: "Unit", power: 3, faction: "Klasztor", row: "melee", abilities: ["muster"], isHero: false, baseId: "Straznik_klasztoru" },
    { id: "Opolos", name: "Opolos", type: "Unit", power: 4, faction: "Klasztor", row: "ranged", isHero: false },
    { id: "Parlan", name: "Parlan", type: "Unit", power: 5, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Isgaroth", name: "Isgaroth", type: "Unit", power: 5, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Daron", name: "Daron", type: "Unit", power: 5, faction: "Klasztor", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Mag_Ognia_1", name: "Mag Ognia", type: "Unit", power: 5, faction: "Klasztor", row: "melee", abilities: ["muster"], isHero: false, baseId: "Mag_Ognia" },
    { id: "Mag_Ognia_2", name: "Mag Ognia", type: "Unit", power: 5, faction: "Klasztor", row: "melee", abilities: ["muster"], isHero: false, baseId: "Mag_Ognia" },
    { id: "Mag_Ognia_3", name: "Mag Ognia", type: "Unit", power: 5, faction: "Klasztor", row: "melee", abilities: ["muster"], isHero: false, baseId: "Mag_Ognia" },
    { id: "Nowicjusz_1", name: "Nowicjusz", type: "Unit", power: 5, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Nowicjusz_2", name: "Nowicjusz", type: "Unit", power: 5, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Nowicjusz_3", name: "Nowicjusz", type: "Unit", power: 5, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Nowicjusz_4", name: "Nowicjusz", type: "Unit", power: 5, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Nowicjusz_5", name: "Nowicjusz", type: "Unit", power: 5, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Rodriguez", name: "Rodriguez", type: "Unit", power: 5, faction: "Klasztor", row: "ranged", isHero: false },
    { id: "Torrez", name: "Torrez", type: "Unit", power: 5, faction: "Klasztor", row: "ranged", isHero: false },
    { id: "Damarok", name: "Damarok", type: "Unit", power: 6, faction: "Klasztor", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Drago", name: "Drago", type: "Unit", power: 6, faction: "Klasztor", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Corristo", name: "Corristo", type: "Unit", power: 6, faction: "Klasztor", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Marduk", name: "Marduk", type: "Unit", power: 6, faction: "Klasztor", row: "ranged", isHero: false },
    { id: "Hyglas", name: "Hyglas", type: "Unit", power: 6, faction: "Klasztor", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Neoras", name: "Neoras", type: "Unit", power: 6, faction: "Klasztor", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Pedro", name: "Pedro", type: "Unit", power: 6, faction: "Klasztor", row: "melee", isHero: false },
    { id: "Jorgen", name: "Jorgen", type: "Unit", power: 6, faction: "Klasztor", row: "ranged", isHero: true },
    { id: "Talamon", name: "Talamon", type: "Unit", power: 8, faction: "Klasztor", row: "siege", abilities: ["scorch_row"], isHero: false },
    { id: "Gorax", name: "Gorax", type: "Unit", power: 10, faction: "Klasztor", row: "ranged", abilities: ["morale_boost"], isHero: true },
    { id: "Serpentes", name: "Serpentes", type: "Unit", power: 10, faction: "Klasztor", row: "ranged", isHero: true },
    { id: "Pyrokar", name: "Pyrokar", type: "Unit", power: 10, faction: "Klasztor", row: "ranged", isHero: true },
    { id: "Lzy_Innosa", name: "Łzy Innosa", type: "Unit", power: 10, faction: "Klasztor", row: "melee", abilities: ["morale_boost"], isHero: true },
    { id: "Ulthar", name: "Ulthar", type: "Unit", power: 10, faction: "Klasztor", row: "ranged", isHero: true },
    { id: "Swieta_Aura_Innosa", name: "Święta Aura Innosa", type: "Leader", faction: "Klasztor", abilities: ['leader_ranged_boost'] },
    { id: "Nabor_nowicjuszy", name: "Nabór nowicjuszy", type: "Leader", faction: "Klasztor", abilities: ['leader_simulate_use'] },
    { id: "Tarcza_Dominique", name: "Tarcza Dominique", type: "Leader", faction: "Klasztor", abilities: ['leader_mplay_rain'] },
    { id: "Klasztorny_rygor", name: "Klasztorny rygor", type: "Leader", faction: "Klasztor",  abilities: ['leader_agile_move'] },
    { id: "Swiety_Mlot_Innosa", name: "Święty Młot Innosa", type: "Leader", faction: "Klasztor", abilities: ['leader_scorch_melee'] },
    { id: "Sergio", name: "Sergio", type: "Unit", power: 0, faction: "Klasztor", row: "melee", isHero: false, isToken: true },

    // ==================================================================
    // === ORKOWIE
    // ==================================================================
    { id: "Orkowa_mapa_wojenna", name: "Orkowa mapa wojenna", type: "Unit", power: 0, faction: "Orkowie", row: "melee", abilities: ["summon_next_round"], isHero: false, isToken: false, nextRoundSummonId: "Herszt_orkow" },
    { id: "Orkowy_bebniarz", name: "Orkowy bębniarz", type: "Unit", power: 2, faction: "Orkowie", row: "siege", abilities: ["morale_boost"] },
    { id: "Tarrok", name: "Tarrok", type: "Unit", power: 2, faction: "Orkowie", row: "melee", abilities: ["medic"] },
    { id: "Kasacz_1", name: "Kąsacz", type: "Unit", power: 2, faction: "Orkowie", row: "ranged", abilities: ["Moc"], transformId: "Wsciekly_kasacz_1", baseId: "Kasacz" },
    { id: "Kasacz_2", name: "Kąsacz", type: "Unit", power: 2, faction: "Orkowie", row: "ranged", abilities: ["Moc"], transformId: "Wsciekly_kasacz_2", baseId: "Kasacz" },
    { id: "Kasacz_3", name: "Kąsacz", type: "Unit", power: 2, faction: "Orkowie", row: "ranged", abilities: ["Moc"], transformId: "Wsciekly_kasacz_3", baseId: "Kasacz" },
    { id: "Ork_wiarus_1", name: "Ork wiarus", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["Moc"], transformId: "Fanatyczny_wiarus_1", baseId: "Wiarus" },
    { id: "Ork_wiarus_2", name: "Ork wiarus", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["Moc"], isHero: false, transformId: "Fanatyczny_wiarus_2", baseId: "Wiarus" },
    { id: "Orkowy_kusznik_1", name: "Orkowy kusznik", type: "Unit", power: 4, faction: "Orkowie", row: "ranged", abilities: ["muster"], isHero: false },
    { id: "Orkowy_kusznik_2", name: "Orkowy kusznik", type: "Unit", power: 4, faction: "Orkowie", row: "ranged", abilities: ["muster"], isHero: false },
    { id: "Orkowy_kusznik_3", name: "Orkowy kusznik", type: "Unit", power: 4, faction: "Orkowie", row: "ranged", abilities: ["muster"], isHero: false },
    { id: "Ork_z_miasta", name: "Ork z miasta", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_zwiadowca", name: "Ork zwiadowca", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Opiekun_swiatyni", name: "Opiekun świątyni", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Orkowy_pies", name: "Orkowy pies", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_mysliwy", name: "Ork myśliwy", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Orkowy_taran", name: "Orkowy taran", type: "Unit", power: 4, faction: "Orkowie", row: "siege", isHero: false },
    { id: "Ork_wojownik_1", name: "Ork wojownik", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["tight_bond", "muster"], isHero: false, isToken: true, baseId: "Ork_wojownik", musterRole: "slug" },
    { id: "Ork_wojownik_2", name: "Ork wojownik", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["tight_bond", "muster"], isHero: false, isToken: true, baseId: "Ork_wojownik", musterRole: "slug" },
    { id: "Ork_wojownik_3", name: "Ork wojownik", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["tight_bond", "muster"], isHero: false, isToken: true, baseId: "Ork_wojownik", musterRole: "slug" },
    { id: "Warg_1", name: "Warg", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", isHero: false },
    { id: "Warg_2", name: "Warg", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", isHero: false },
    { id: "Warg_3", name: "Warg", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", isHero: false },
    { id: "Ork_szaman", name: "Ork szaman", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", abilities: ["scorch"], isHero: false },
    { id: "Ork_zolnierz", name: "Ork żołnierz", type: "Unit", power: 6, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_straznik", name: "Ork strażnik", type: "Unit", power: 6, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_elita_1", name: "Ork elita", type: "Unit", power: 6, faction: "Orkowie", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Ork_elita" },
    { id: "Ork_elita_2", name: "Ork elita", type: "Unit", power: 6, faction: "Orkowie", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Ork_elita" },
    { id: "Ork_elita_3", name: "Ork elita", type: "Unit", power: 6, faction: "Orkowie", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Ork_elita" },
    { id: "Dowodca_grupy_1", name: "Dowódca grupy", type: "Unit", power: 6, faction: "Orkowie", row: "siege", abilities: ["tight_bond"], isHero: false },
    { id: "Dowodca_grupy_2", name: "Dowódca grupy", type: "Unit", power: 6, faction: "Orkowie", row: "siege", abilities: ["tight_bond"], isHero: false },
    { id: "Dowodca_grupy_3", name: "Dowódca grupy", type: "Unit", power: 6, faction: "Orkowie", row: "siege", abilities: ["tight_bond"], isHero: false },
    { id: "Wsciekly_kasacz_1", name: "Wściekły kąsacz", type: "Unit", power: 8, faction: "Orkowie", row: "ranged", abilities: ["tight_bond"], isHero: false, isToken: true, baseId: "Wsciekly_kasacz" },
    { id: "Wsciekly_kasacz_2", name: "Wściekły kąsacz", type: "Unit", power: 8, faction: "Orkowie", row: "ranged", abilities: ["tight_bond"], isHero: false, isToken: true, baseId: "Wsciekly_kasacz" },
    { id: "Wsciekly_kasacz_3", name: "Wściekły kąsacz", type: "Unit", power: 8, faction: "Orkowie", row: "ranged", abilities: ["tight_bond"], isHero: false, isToken: true, baseId: "Wsciekly_kasacz" },
    { id: "Orkowy_treser", name: "Orkowy treser", type: "Unit", power: 8, faction: "Orkowie", row: "ranged", abilities: ["Wyzwolenie siły"], isHero: true, transformTargetId: ["Kasacz"] },
    { id: "Ur-Shak", name: "Ur-Shak", type: "Unit", power: 10, faction: "Orkowie", row: "ranged", isHero: true },
    { id: "Hosh-Pak", name: "Hosh-Pak", type: "Unit", power: 10, faction: "Orkowie", row: "melee", abilities: ["muster"], isHero: true, musterRole: "master" },
    { id: "Herszt_orkow", name: "Herszt orków", type: "Unit", power: 11, faction: "Orkowie", row: "melee", isHero: true, isToken: true },
    { id: "Ork_pulkownik", name: "Ork pułkownik", type: "Unit", power: 12, faction: "Orkowie", row: ["melee", "ranged"], abilities: ["agile", "morale_boost"], isHero: false },
    { id: "Fanatyczny_wiarus_1", name: "Fanatyczny wiarus", type: "Unit", power: 14, faction: "Orkowie", row: "melee", abilities: ["morale_boost"], isHero: false, isToken: true, baseId: "Fanatyczny_wiarus" },
    { id: "Fanatyczny_wiarus_2", name: "Fanatyczny wiarus", type: "Unit", power: 14, faction: "Orkowie", row: "melee", abilities: ["morale_boost"], isHero: false, isToken: true, baseId: "Fanatyczny_wiarus" },
    { id: "Magia_Braci", name: "Magia Braci", type: "Weather", faction: "Orkowie", rowAffected: ["ranged", "siege"], effectClass: "fear-effect" },
    { id: "Ulu-Mulu", name: "Ulu-Mulu", type: "Special", faction: "Orkowie", abilities: ["Wyzwolenie siły"], transformTargetId: ["Kasacz", "Wiarus"] },
    { id: "Zew_hordy", name: "Zew hordy", type: "Leader", faction: "Orkowie", abilities: ['leader_unleash_all_power'] },
    { id: "Wojna_totalna", name: "Wojna totalna", type: "Leader", faction: "Orkowie", abilities: ['leader_destroy_opponent_graveyard'] },
    { id: "Beliar_z_nami", name: "Beliar z nami", type: "Leader", faction: "Orkowie", abilities: ['leader_weather_resistance'] },
    { id: "Ork_niewolnik", name: "Ork niewolnik", type: "Unit", power: 0, faction: "Orkowie", row: "siege", isHero: false, isToken: true },
    { id: "Ogar", name: "Ogar", type: "Unit", power: 0, faction: "Orkowie", row: "siege", isHero: false, isToken: true },
    { id: "Wodz_hordy", name: "Wódz hordy", type: "Unit", power: 0, faction: "Orkowie", row: "siege", isHero: false, isToken: true },

    // ==================================================================
    // === BANDYCI
    // ==================================================================
    { id: "Mily_bandyta", name: "Miły bandyta", type: "Unit", power: 1, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Paul", name: "Paul", type: "Unit", power: 1, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Huno", name: "Huno", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Crimson", name: "Crimson", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Fernando", name: "Fernando", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["spy"], isHero: false },
    { id: "Snaf", name: "Snaf", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Rabus_1", name: "Rabuś", type: "Unit", power: 1, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Rabus" },
    { id: "Rabus_2", name: "Rabuś", type: "Unit", power: 1, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Rabus" },
    { id: "Rozbojnik", name: "Rozbójnik", type: "Unit", power: 2, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Lucia", name: "Lucia", type: "Unit", power: 2, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Brago", name: "Brago", type: "Unit", power: 4, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Finn", name: "Finn", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "FinnEmilioLennar" },
    { id: "Emilio", name: "Emilio", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "FinnEmilioLennar" },
    { id: "Lennar", name: "Lennar", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "FinnEmilioLennar" },
    { id: "Senyan", name: "Senyan", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Logan", name: "Logan", type: "Unit", power: 4, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Tom", name: "Tom", type: "Unit", power: 5, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Bandyta_1", name: "Bandyta", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "Bandyta" },
    { id: "Bandyta_2", name: "Bandyta", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "Bandyta" },
    { id: "Bandyta_3", name: "Bandyta", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "Bandyta" },
    { id: "Sancho", name: "Sancho", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Fisk", name: "Fisk", type: "Unit", power: 5, faction: "Bandyci", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Miguel", name: "Miguel", type: "Unit", power: 5, faction: "Bandyci", row: "siege", abilities: ["medic"], isHero: false },
    { id: "Edgor", name: "Edgor", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Scatty", name: "Scatty", type: "Unit", power: 5, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Garaz", name: "Garaz", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Franko", name: "Franko", type: "Unit", power: 6, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Skinner", name: "Skinner", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Ramon", name: "Ramon", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Carlos", name: "Carlos", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Juan", name: "Juan", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Esteban", name: "Esteban", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Straznik_Kruka_1", name: "Strażnik Kruka", type: "Unit", power: 8, faction: "Bandyci", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "Straznik_Kruka" },
    { id: "Straznik_Kruka_2", name: "Strażnik Kruka", type: "Unit", power: 8, faction: "Bandyci", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "Straznik_Kruka" },
    { id: "Dexter", name: "Dexter", type: "Unit", power: 10, faction: "Bandyci", row: "ranged", isHero: true },
    { id: "Bloodwyn", name: "Bloodwyn", type: "Unit", power: 10, faction: "Bandyci", row: "melee", isHero: true },
    { id: "Kruk", name: "Kruk", type: "Unit", power: 10, faction: "Bandyci", row: "melee", isHero: true },
    { id: "Thorus", name: "Thorus", type: "Unit", power: 10, faction: "Bandyci", row: "melee", isHero: true },
    { id: "Uklady", name: "Układy", type: "Leader", faction: "Bandyci", abilities: ['leader_cancel_opponent_ability'] },
    { id: "Ukryci_wsrod_drzew", name: "Ukryci wśród drzew", type: "Leader", faction: "Bandyci", abilities: ['leader_scorch_melee'] },
    { id: "Quentin", name: "Quentin", type: "Unit", power: 0, faction: "Bandyci", isHero: false, isToken: true },
    { id: "Wloczega", name: "Włóczęga", type: "Unit", power: 4, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Straznik_niewolnikow", name: "Strażnik niewolników", type: "Unit", power: 4, faction: "Bandyci", row: "melee", isHero: false },

    // ==================================================================
    // === NIEUMARLI
    // ==================================================================
    { id: "Szkielet_mag_1", name: "Szkielet mag", type: "Unit", power: 0, faction: "Nieumarli", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Szkielet_mag_2", name: "Szkielet mag", type: "Unit", power: 0, faction: "Nieumarli", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Szkielet_mag_3", name: "Szkielet mag", type: "Unit", power: 0, faction: "Nieumarli", row: "ranged", abilities: ["medic"], isHero: false },
    { id: "Szkielet_goblin_1", name: "Szkielet goblin", type: "Unit", power: 2, faction: "Nieumarli", row: "ranged", abilities: ["muster"], isHero: false, baseId: "Szkielet_goblin" },
    { id: "Szkielet_goblin_2", name: "Szkielet goblin", type: "Unit", power: 2, faction: "Nieumarli", row: "ranged", abilities: ["muster"], isHero: false, baseId: "Szkielet_goblin" },
    { id: "Szkielet_goblin_3", name: "Szkielet goblin", type: "Unit", power: 2, faction: "Nieumarli", row: "ranged", abilities: ["muster"], isHero: false, baseId: "Szkielet_goblin" },
    { id: "Blotniak", name: "Błotniak", type: "Unit", power: 2, faction: "Nieumarli", row: "ranged", isHero: false },
    { id: "Nadzorca", name: "Nadzorca", type: "Unit", power: 3, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Pomniejszy_szkielet_1", name: "Pomniejszy szkielet", type: "Unit", power: 3, faction: "Nieumarli", row: "melee", abilities: ["muster"], isHero: false, baseId: "Pomniejszy_szkielet" },
    { id: "Pomniejszy_szkielet_2", name: "Pomniejszy szkielet", type: "Unit", power: 3, faction: "Nieumarli", row: "melee", abilities: ["muster"], isHero: false, baseId: "Pomniejszy_szkielet" },
    { id: "Pomniejszy_szkielet_3", name: "Pomniejszy szkielet", type: "Unit", power: 3, faction: "Nieumarli", row: "melee", abilities: ["muster"], isHero: false, baseId: "Pomniejszy_szkielet" },
    { id: "Straznik_krypty", name: "Strażnik krypty", type: "Unit", power: 4, faction: "Nieumarli", row: "ranged", isHero: false },
    { id: "Szkielet_zwiadowca", name: "Szkielet zwiadowca", type: "Unit", power: 4, faction: "Nieumarli", row: "ranged", isHero: false },
    { id: "Szkielet_wojownik_1", name: "Szkielet wojownik", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", abilities: ["muster"], isHero: false, baseId: "Szkielet_wojownik" },
    { id: "Szkielet_wojownik_2", name: "Szkielet wojownik", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", abilities: ["muster"], isHero: false, baseId: "Szkielet_wojownik" },
    { id: "Szkielet_wojownik_3", name: "Szkielet wojownik", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", abilities: ["muster"], isHero: false, baseId: "Szkielet_wojownik" },
    { id: "Zombie_1", name: "Zombie", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", isHero: false },
    { id: "Zombie_2", name: "Zombie", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", isHero: false },
    { id: "Zombie_3", name: "Zombie", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", isHero: false },
    { id: "Zombie_4", name: "Zombie", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", isHero: false },
    { id: "Zombie_5", name: "Zombie", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", isHero: false },
    { id: "Varrag-Hashor", name: "Varrag-Hashor", type: "Unit", power: 5, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Grash-Varrag-Arushat", name: "Grash-Varrag-Arushat", type: "Unit", power: 5, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Demon", name: "Demon", type: "Unit", power: 6, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Zombie_straznik", name: "Zombie strażnik", type: "Unit", power: 6, faction: "Nieumarli", row: "melee", isHero: false },
    { id: "Szkielet_cieniostwor", name: "Szkielet cieniostwór", type: "Unit", power: 6, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Poszukiwacz_1", name: "Poszukiwacz", type: "Unit", power: 6, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Poszukiwacz_2", name: "Poszukiwacz", type: "Unit", power: 6, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Poszukiwacz_3", name: "Poszukiwacz", type: "Unit", power: 6, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Mag_z_Wiezy_Mgiel", name: "Mag z Wieży Mgieł", type: "Unit", power: 6, faction: "Nieumarli", row: "ranged", isHero: false },
    { id: "Wojownik_Cienia", name: "Wojownik Cienia", type: "Unit", power: 6, faction: "Nieumarli", row: ["melee", "ranged"], abilities: ["agile"], isHero: false },
    { id: "Czarny_mag", name: "Czarny mag", type: "Unit", power: 8, faction: "Nieumarli", row: "siege", abilities: ["scorch_row"], isHero: false },
    { id: "Klucznik", name: "Klucznik", type: "Unit", power: 10, faction: "Nieumarli", row: "ranged", abilities: ["morale_boost"], isHero: false },
    { id: "Pan_Cienia_Inubis", name: "Pan Cienia Inubis", type: "Unit", power: 10, faction: "Nieumarli", row: "ranged", isHero: true },
    { id: "Pan_Cienia_Archol", name: "Pan Cienia Archol", type: "Unit", power: 10, faction: "Nieumarli", row: "ranged", isHero: true },
    { id: "Ksiaze_demonow", name: "Książę demonów", type: "Unit", power: 10, faction: "Nieumarli", row: "melee", abilities: ["morale_boost"], isHero: true },
    { id: "Smok_Ozywieniec", name: "Smok Ożywieniec", type: "Unit", power: 10, faction: "Nieumarli", row: "ranged", isHero: true },
    { id: "Moc_Dworu_Irdorath", name: "Moc Dworu Irdorath", type: "Leader", faction: "Nieumarli", abilities: ["leader_scorch_melee"] },
    { id: "Mroczny_rytual", name: "Mroczny rytuał", type: "Leader", faction: "Nieumarli", abilities: ["leader_melee_boost"] },
    { id: "Wrota_piekiel", name: "Wrota piekieł", type: "Leader", faction: "Nieumarli", abilities: ["leader_simulate_use"] },
    { id: "Ognisty_demon", name: "Ognisty demon", type: "Unit", power: 4, faction: "Nieumarli", row: "ranged", isHero: false },
    { id: "Mario", name: "Mario", type: "Unit", power: 5, faction: "Nieumarli", row: "melee", isHero: false },
    { id: "Varrag-Kasorg", name: "Varrag-Kasorg", type: "Unit", power: 0, faction: "Nieumarli", row: "melee", isHero: false, isToken: true },
    { id: "Varrag-Unhilqt", name: "Varrag-Unhilqt", type: "Unit", power: 0, faction: "Nieumarli", row: "melee", isHero: false, isToken: true },
    { id: "Varrag-Ruuushk", name: "Varrag-Ruuushk", type: "Unit", power: 0, faction: "Nieumarli", row: "melee", isHero: false, isToken: true },

    // ==================================================================
    // === NEUTRALNE
    // ==================================================================
    { id: "decoy_1", name: "Chrząszcz", type: "Special", faction: "Neutral", abilities: ["decoy"] },
    { id: "decoy_2", name: "Chrząszcz", type: "Special", faction: "Neutral", abilities: ["decoy"] },
    { id: "decoy_3", name: "Chrząszcz", type: "Special", faction: "Neutral", abilities: ["decoy"] },
    { id: "commanders_horn_1", name: "Róg wojenny", type: "Special", faction: "Neutral", abilities: ["horn"] },
    { id: "commanders_horn_2", name: "Róg wojenny", type: "Special", faction: "Neutral", abilities: ["horn"] },
    { id: "commanders_horn_3", name: "Róg wojenny", type: "Special", faction: "Neutral", abilities: ["horn"] },
    { id: "clear_weather_1", name: "Światło", type: "Weather", faction: "Neutral", rowAffected: null },
    { id: "clear_weather_2", name: "Światło", type: "Weather", faction: "Neutral", rowAffected: null },
    { id: "clear_weather_3", name: "Światło", type: "Weather", faction: "Neutral", rowAffected: null },
    { id: "torrential_rain_1", name: "Grom", type: "Weather", faction: "Neutral", rowAffected: ["siege"], effectClass: "frost-effect" },
    { id: "torrential_rain_2", name: "Grom", type: "Weather", faction: "Neutral", rowAffected: ["siege"], effectClass: "frost-effect" },
    { id: "torrential_rain_3", name: "Grom", type: "Weather", faction: "Neutral", rowAffected: ["siege"], effectClass: "frost-effect" },
    { id: "impenetrable_fog_1", name: "Rój owadów", type: "Weather", faction: "Neutral", rowAffected: ["ranged"], effectClass: "fog-effect" },
    { id: "impenetrable_fog_2", name: "Rój owadów", type: "Weather", faction: "Neutral", rowAffected: ["ranged"], effectClass: "fog-effect" },
    { id: "impenetrable_fog_3", name: "Rój owadów", type: "Weather", faction: "Neutral", rowAffected: ["ranged"], effectClass: "fog-effect" },
    { id: "biting_frost_1", name: "Lodowa fala", type: "Weather", faction: "Neutral", rowAffected: ["melee"], effectClass: "frost-effect" },
    { id: "biting_frost_2", name: "Lodowa fala", type: "Weather", faction: "Neutral", rowAffected: ["melee"], effectClass: "frost-effect" },
    { id: "biting_frost_3", name: "Lodowa fala", type: "Weather", faction: "Neutral", rowAffected: ["melee"], effectClass: "frost-effect" },
    { id: "scorch_1", name: "Deszcz ognia", type: "Special", faction: "Neutral", abilities: ["scorch_strongest"] },
    { id: "scorch_2", name: "Deszcz ognia", type: "Special", faction: "Neutral", abilities: ["scorch_strongest"] },
    { id: "scorch_3", name: "Deszcz ognia", type: "Special", faction: "Neutral", abilities: ["scorch_strongest"] },
    { id: "fear_sower_1", name: "Strach", type: "Special", faction: "Neutral", rowAffected: ["ranged", "siege"], effectClass: "fear-effect" },
    { id: "Wrzod", name: "Wrzód", type: "Unit", power: 0, faction: "Neutral", row: "melee", abilities: ["spy"], isHero: true, description: "Hej kolego!" },
    { id: "Lester", name: "Lester", type: "Unit", power: 2, faction: "Neutral", row: "melee", abilities: ["horn"], isHero: false },
    { id: "Kamienny_golem", name: "Kamienny golem", type: "Unit", power: 5, faction: "Neutral", row: "siege", isHero: false },
    { id: "Diego", name: "Diego", type: "Unit", power: 6, faction: "Neutral", row: ["melee", "ranged"], abilities: ["agile", "morale_boost"], isHero: false },
    { id: "Ryzowy_Ksiaze", name: "Ryżowy Książę", type: "Unit", power: 6, faction: "Neutral", row: "melee", isHero: true },
    { id: "Milten", name: "Milten", type: "Unit", power: 7, faction: "Neutral", row: "melee", abilities: ["scorch_row"], isHero: false },
    { id: "Lares", name: "Lares", type: "Unit", power: 7, faction: "Neutral", row: "melee", isHero: true },
    { id: "Cavalorn", name: "Cavalorn", type: "Unit", power: 5, faction: "Neutral", row: "ranged", isHero: false },
    { id: "Vatras", name: "Vatras", type: "Unit", power: 7, faction: "Neutral", row: "melee", abilities: ["medic"], isHero: true },
    { id: "Xardas", name: "Xardas", type: "Unit", power: 0, faction: "Neutral", row: "ranged", abilities: ["avenger"], isHero: false, summons: "Demon_Ognia" },
    { id: "Demon_Ognia", name: "Demon Ognia", type: "Unit", power: 11, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Gorn", name: "Gorn", type: "Unit", power: 15, faction: "Neutral", row: "melee", isHero: true },
    { id: "Bezimienny", name: "Bezimienny", type: "Unit", power: 15, faction: "Neutral", row: "melee", isHero: true, description: "Jestem..." },
    { id: "Saturas", name: "Saturas", type: "Unit", power: 2, faction: "Neutral", row: "siege", abilities: ["muster"], isHero: false, musterRole: "master", baseId: "Czlowiek_woda" },
    { id: "Riordian", name: "Riordian", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "Czlowiek_woda" },
    { id: "Cronos", name: "Cronos", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "Czlowiek_woda" },
    { id: "Nefarius", name: "Nefarius", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "Czlowiek_woda" },
    { id: "Myxir", name: "Myxir", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "Czlowiek_woda" },
    { id: "Merdarion", name: "Merdarion", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "Czlowiek_woda" },
    { id: "Grimes", name: "Grimes", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false },
    { id: "Sedzia", name: "Sędzia", type: "Unit", power: 4, faction: "Neutral", row: "siege", isHero: false },
    { id: "Gestath", name: "Gestath", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Cavalorn_token", name: "Cavalorn", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Kamienny_straznik", name: "Kamienny strażnik", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Bagienny_golem", name: "Bagienny golem", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Ognisty_golem", name: "Ognisty golem", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Lodowy_golem", name: "Lodowy golem", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
];