const allCards = [
    // ==================================================================
    // === KARTY NEUTRALNE (ZAKTUALIZOWANE)
    // ==================================================================
    { id: "decoy_1", name: "Chrząszcz", type: "Special", faction: "Neutral", abilities: ["decoy"] },
    { id: "decoy_2", name: "Chrząszcz", type: "Special", faction: "Neutral", abilities: ["decoy"] },
    { id: "decoy_3", name: "Chrząszcz", type: "Special", faction: "Neutral", abilities: ["decoy"] },
    { id: "commanders_horn_1", name: "Róg wojenny", type: "Special", faction: "Neutral", abilities: ["horn"] },
    { id: "commanders_horn_2", name: "Róg wojenny", type: "Special", faction: "Neutral", abilities: ["horn"] },
    { id: "commanders_horn_3", name: "Róg wojenny", type: "Special", faction: "Neutral", abilities: ["horn"] },
    { id: "clear_weather_1", name: "Światło", type: "Weather", faction: "Neutral", rowAffected: null },
    { id: "clear_weather_2", name: "Światło", type: "Weather", faction: "Neutral", rowAffected: null },
    { id: "clear_weather_3", name: "Światło", type: "Weather", faction: "Neutral", rowAffected: null },
    { id: "torrential_rain_1", name: "Grom", type: "Weather", faction: "Neutral", rowAffected: ["siege"], effectClass: "rain-effect" },
    { id: "torrential_rain_2", name: "Grom", type: "Weather", faction: "Neutral", rowAffected: ["siege"], effectClass: "rain-effect" },
    { id: "torrential_rain_3", name: "Grom", type: "Weather", faction: "Neutral", rowAffected: ["siege"], effectClass: "rain-effect" },
    { id: "impenetrable_fog_1", name: "Rój owadów", type: "Weather", faction: "Neutral", rowAffected: ["ranged"], effectClass: "fog-effect" },
    { id: "impenetrable_fog_2", name: "Rój owadów", type: "Weather", faction: "Neutral", rowAffected: ["ranged"], effectClass: "fog-effect" },
    { id: "impenetrable_fog_3", name: "Rój owadów", type: "Weather", faction: "Neutral", rowAffected: ["ranged"], effectClass: "fog-effect" },
    { id: "biting_frost_1", name: "Lodowa fala", type: "Weather", faction: "Neutral", rowAffected: ["melee"], effectClass: "frost-effect" },
    { id: "biting_frost_2", name: "Lodowa fala", type: "Weather", faction: "Neutral", rowAffected: ["melee"], effectClass: "frost-effect" },
    { id: "biting_frost_3", name: "Lodowa fala", type: "Weather", faction: "Neutral", rowAffected: ["melee"], effectClass: "frost-effect" },
    { id: "scorch_1", name: "Deszcz ognia", type: "Special", faction: "Neutral", abilities: ["scorch_strongest"] },
    { id: "scorch_2", name: "Deszcz ognia", type: "Special", faction: "Neutral", abilities: ["scorch_strongest"] },
    { id: "scorch_3", name: "Deszcz ognia", type: "Special", faction: "Neutral", abilities: ["scorch_strongest"] },
    { id: "fear_sower_1", name: "Strach", type: "Weather", faction: "Neutral", rowAffected: ["ranged", "siege"], effectClass: "fear-effect" },
    { id: "Wrzod", name: "Wrzód", type: "Unit", power: 0, faction: "Neutral", row: "melee", abilities: ["spy"], isHero: true, description: "Hej kolego!" },
    { id: "Lester", name: "Lester", type: "Unit", power: 2, faction: "Neutral", row: "melee", abilities: ["horn"], isHero: false },
    { id: "Kamienny_golem", name: "Kamienny golem", type: "Unit", power: 5, faction: "Neutral", row: "siege", isHero: false },
    { id: "Diego", name: "Diego", type: "Unit", power: 6, faction: "Neutral", row: ["melee", "ranged"], abilities: ["agile", "morale_boost"], isHero: false },
    { id: "Ryzowy_Ksiaze", name: "Ryżowy Książę", type: "Unit", power: 6, faction: "Neutral", row: "melee", isHero: true },
    { id: "Milten", name: "Milten", type: "Unit", power: 7, faction: "Neutral", row: "melee", abilities: ["scorch_row"], isHero: false },
    { id: "Lares", name: "Lares", type: "Unit", power: 7, faction: "Neutral", row: "melee", isHero: true },
    { id: "Cavalorn_1", name: "Cavalorn", type: "Unit", power: 5, faction: "Neutral", row: "ranged", isHero: false },
    { id: "Vatras", name: "Vatras", type: "Unit", power: 7, faction: "Neutral", row: "melee", abilities: ["medic"], isHero: true },
    { id: "Xardas", name: "Xardas", type: "Unit", power: 0, faction: "Neutral", row: "ranged", abilities: ["avenger"], isHero: false, summons: "Demon_Ognia" },
    { id: "Demon_Ognia", name: "Demon Ognia", type: "Unit", power: 11, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Gorn_1", name: "Gorn", type: "Unit", power: 15, faction: "Neutral", row: "melee", isHero: true },
    { id: "Bezimienny", name: "Bezimienny", type: "Unit", power: 15, faction: "Neutral", row: "melee", isHero: true },
    { id: "Saturas", name: "Saturas", type: "Unit", power: 2, faction: "Neutral", row: "siege", abilities: ["muster"], isHero: false, musterRole: "master", baseId: "magowie_wody" },
    { id: "Riordian", name: "Riordian", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "magowie_wody" },
    { id: "Cronos", name: "Cronos", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "magowie_wody" },
    { id: "Nefarius", name: "Nefarius", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "magowie_wody" },
    { id: "Myxir", name: "Myxir", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "magowie_wody" },
    { id: "Merdarion", name: "Merdarion", type: "Unit", power: 3, faction: "Neutral", row: "ranged", abilities: ["muster"], isHero: false, musterRole: "slug", baseId: "magowie_wody" },
    { id: "Grimes", name: "Grimes", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false },
    { id: "Sedzia", name: "Sędzia", type: "Unit", power: 4, faction: "Neutral", row: "siege", isHero: false },
    { id: "Gestath", name: "Gestath", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Cavalorn_2", name: "Cavalorn", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Kamienny_straznik", name: "Kamienny strażnik", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Bagienny_golem", name: "Bagienny golem", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Ognisty_golem", name: "Ognisty golem", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },
    { id: "Lodowy_golem", name: "Lodowy golem", type: "Unit", power: 0, faction: "Neutral", row: "melee", isHero: false, isToken: true },

    // ==================================================================
    // === ORKOWIE
    // ==================================================================
    { id: "Zew_hordy", name: "Zew hordy", type: "Leader", faction: "Orkowie", abilities: ["leader_unleash_all_power"] },
    { id: "Wojna_totalna", name: "Wojna totalna", type: "Leader", faction: "Orkowie", abilities: ["leader_destroy_opponent_graveyard"] },
    { id: "Beliar_z_nami", name: "Beliar z nami", type: "Leader", faction: "Orkowie" },
    { id: "Orkowa_mapa_wojenna", name: "Orkowa mapa wojenna", type: "Unit", power: 0, faction: "Orkowie", row: "melee", abilities: ["summon_next_round"], isHero: false, isToken: false, nextRoundSummonId: "Herszt_orkow" },
    { id: "Orkowy_bebniarz", name: "Orkowy bębniarz", type: "Unit", power: 2, faction: "Orkowie", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Tarrok", name: "Tarrok", type: "Unit", power: 2, faction: "Orkowie", row: "melee", abilities: ["medic"], isHero: false },
    { id: "Kasacz_1", name: "Kąsacz", type: "Unit", power: 2, faction: "Orkowie", row: "ranged", abilities: ["Moc"], isHero: false, baseId: "kasacz", transformId: "wsciekly_kasacz_token" },
    { id: "Kasacz_2", name: "Kąsacz", type: "Unit", power: 2, faction: "Orkowie", row: "ranged", abilities: ["Moc"], isHero: false, baseId: "kasacz", transformId: "wsciekly_kasacz_token" },
    { id: "Kasacz_3", name: "Kąsacz", type: "Unit", power: 2, faction: "Orkowie", row: "ranged", abilities: ["Moc"], isHero: false, baseId: "kasacz", transformId: "wsciekly_kasacz_token" },
    { id: "Ork_wiarus_1", name: "Ork wiarus", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["Moc"], isHero: false, baseId: "wiarus", transformId: "fanatyczny_wiarus_token" },
    { id: "Ork_wiarus_2", name: "Ork wiarus", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["Moc"], isHero: false, baseId: "wiarus", transformId: "fanatyczny_wiarus_token" },
    { id: "Orkowy_kusznik_1", name: "Orkowy kusznik", type: "Unit", power: 4, faction: "Orkowie", row: "ranged", abilities: ["muster"], isHero: false, baseId: "orkowy_kusznik" },
    { id: "Orkowy_kusznik_2", name: "Orkowy kusznik", type: "Unit", power: 4, faction: "Orkowie", row: "ranged", abilities: ["muster"], isHero: false, baseId: "orkowy_kusznik" },
    { id: "Orkowy_kusznik_3", name: "Orkowy kusznik", type: "Unit", power: 4, faction: "Orkowie", row: "ranged", abilities: ["muster"], isHero: false, baseId: "orkowy_kusznik" },
    { id: "Ork_z_miasta", name: "Ork z miasta", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_zwiadowca", name: "Ork zwiadowca", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Opiekun_swiatyni", name: "Opiekun świątyni", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Orkowy_pies", name: "Orkowy pies", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_mysliwy", name: "Ork myśliwy", type: "Unit", power: 4, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Orkowy_taran", name: "Orkowy taran", type: "Unit", power: 4, faction: "Orkowie", row: "siege", isHero: false },
    { id: "Ork_wojownik_1", name: "Ork wojownik", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["tight_bond", "muster"], isHero: false, isToken: true, baseId: "Ork_wojownik", musterRole: "slug" },
    { id: "Ork_wojownik_2", name: "Ork wojownik", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["tight_bond", "muster"], isHero: false, isToken: true, baseId: "Ork_wojownik", musterRole: "slug" },
    { id: "Ork_wojownik_3", name: "Ork wojownik", type: "Unit", power: 4, faction: "Orkowie", row: "melee", abilities: ["tight_bond", "muster"], isHero: false, isToken: true, baseId: "Ork_wojownik", musterRole: "slug" },
    { id: "Warg_1", name: "Warg", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", isHero: false },
    { id: "Warg_2", name: "Warg", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", isHero: false },
    { id: "Warg_3", name: "Warg", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", isHero: false },
    { id: "Ork_szaman", name: "Ork szaman", type: "Unit", power: 6, faction: "Orkowie", row: "ranged", abilities: ["scorch_row"], isHero: false },
    { id: "Ork_zolnierz", name: "Ork żołnierz", type: "Unit", power: 6, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_straznik", name: "Ork strażnik", type: "Unit", power: 6, faction: "Orkowie", row: "melee", isHero: false },
    { id: "Ork_elita_1", name: "Ork elita", type: "Unit", power: 6, faction: "Orkowie", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Ork_elita" },
    { id: "Ork_elita_2", name: "Ork elita", type: "Unit", power: 6, faction: "Orkowie", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Ork_elita" },
    { id: "Ork_elita_3", name: "Ork elita", type: "Unit", power: 6, faction: "Orkowie", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "Ork_elita" },
    { id: "Dowodca_grupy_1", name: "Dowódca grupy", type: "Unit", power: 6, faction: "Orkowie", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "dowodca_grupy" },
    { id: "Dowodca_grupy_2", name: "Dowódca grupy", type: "Unit", power: 6, faction: "Orkowie", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "dowodca_grupy" },
    { id: "Dowodca_grupy_3", name: "Dowódca grupy", type: "Unit", power: 6, faction: "Orkowie", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "dowodca_grupy" },
    { id: "wsciekly_kasacz_token", name: "Wściekły kąsacz", type: "Unit", power: 8, faction: "Orkowie", row: "ranged", abilities: ["tight_bond"], isHero: false, isToken: true, baseId: "wsciekly_kasacz" },
    { id: "Orkowy_treser", name: "Orkowy treser", type: "Unit", power: 8, faction: "Orkowie", row: "ranged", abilities: ["Wyzwolenie siły"], isHero: true, transformTargetId: "kasacz" },
    { id: "Ur-Shak", name: "Ur-Shak", type: "Unit", power: 10, faction: "Orkowie", row: "ranged", isHero: true },
    { id: "Hosh-Pak", name: "Hosh-Pak", type: "Unit", power: 10, faction: "Orkowie", row: "melee", abilities: ["muster"], isHero: true, baseId: "Ork_wojownik", musterRole: "master" },
    { id: "Herszt_orkow", name: "Herszt orków", type: "Unit", power: 11, faction: "Orkowie", row: "melee", isHero: true, isToken: true },
    { id: "Ork_pulkownik", name: "Ork pułkownik", type: "Unit", power: 12, faction: "Orkowie", row: ["melee", "ranged"], abilities: ["agile", "morale_boost"], isHero: false },
    { id: "fanatyczny_wiarus_token", name: "Fanatyczny wiarus", type: "Unit", power: 14, faction: "Orkowie", row: "melee", abilities: ["morale_boost"], isHero: false, isToken: true },
    { id: "Magia_Braci", name: "Magia Braci", type: "Weather", faction: "Orkowie", rowAffected: ["ranged", "siege"], effectClass: "fear-effect" },
    { id: "Ulu-Mulu", name: "Ulu-Mulu", type: "Special", faction: "Orkowie", abilities: ["horn", "Wyzwolenie siły"], transformTargetId: ["kasacz", "wiarus"] },
    { id: "Ork_niewolnik", name: "Ork niewolnik", type: "Unit", power: 0, faction: "Orkowie", row: "siege", isHero: false, isToken: true },
    { id: "Ogar", name: "Ogar", type: "Unit", power: 0, faction: "Orkowie", row: "siege", isHero: false, isToken: true },
    { id: "Wodz_hordy", name: "Wódz hordy", type: "Unit", power: 0, faction: "Orkowie", row: "siege", isHero: false, isToken: true },

    // ==================================================================
    // === BANDYCI
    // ==================================================================
    { id: "Uklady", name: "Układy", type: "Leader", faction: "Bandyci", abilities: ["leader_cancel_opponent_ability"] },
    { id: "Ukryci_wsrod_drzew", name: "Ukryci wśród drzew", type: "Leader", faction: "Bandyci", abilities: ["leader_play_frost"] },
    { id: "Mily_bandyta", name: "Miły bandyta", type: "Unit", power: 1, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Paul", name: "Paul", type: "Unit", power: 1, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Huno", name: "Huno", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Crimson", name: "Crimson", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Fernando", name: "Fernando", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["spy"], isHero: false },
    { id: "Snaf", name: "Snaf", type: "Unit", power: 1, faction: "Bandyci", row: "siege", abilities: ["morale_boost"], isHero: false },
    { id: "Rabus_1", name: "Rabuś", type: "Unit", power: 1, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "rabus" },
    { id: "Rabus_2", name: "Rabuś", type: "Unit", power: 1, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "rabus" },
    { id: "Rozbojnik", name: "Rozbójnik", type: "Unit", power: 2, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Lucia", name: "Lucia", type: "Unit", power: 2, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Brago", name: "Brago", type: "Unit", power: 4, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Finn", name: "Finn", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "FinnEmilioLennar" },
    { id: "Emilio", name: "Emilio", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "FinnEmilioLennar" },
    { id: "Lennar", name: "Lennar", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["tight_bond"], isHero: false, baseId: "FinnEmilioLennar" },
    { id: "Senyan", name: "Senyan", type: "Unit", power: 4, faction: "Bandyci", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Logan", name: "Logan", type: "Unit", power: 4, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Tom", name: "Tom", type: "Unit", power: 5, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Bandyta_1", name: "Bandyta", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "bandyta" },
    { id: "Bandyta_2", name: "Bandyta", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "bandyta" },
    { id: "Bandyta_3", name: "Bandyta", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", abilities: ["tight_bond"], isHero: false, baseId: "bandyta" },
    { id: "Sancho", name: "Sancho", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Fisk", name: "Fisk", type: "Unit", power: 5, faction: "Bandyci", row: "melee", abilities: ["spy"], isHero: false },
    { id: "Miguel", name: "Miguel", type: "Unit", power: 5, faction: "Bandyci", row: "siege", abilities: ["medic"], isHero: false },
    { id: "Edgor", name: "Edgor", type: "Unit", power: 5, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Scatty", name: "Scatty", type: "Unit", power: 5, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Garaz", name: "Garaz", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Franko", name: "Franko", type: "Unit", power: 6, faction: "Bandyci", row: "ranged", isHero: false },
    { id: "Skinner", name: "Skinner", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Ramon", name: "Ramon", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Carlos", name: "Carlos", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Juan", name: "Juan", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Esteban", name: "Esteban", type: "Unit", power: 6, faction: "Bandyci", row: "siege", isHero: false },
    { id: "Straznik_Kruka_1", name: "Strażnik Kruka", type: "Unit", power: 8, faction: "Bandyci", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "straznik_kruka" },
    { id: "Straznik_Kruka_2", name: "Strażnik Kruka", type: "Unit", power: 8, faction: "Bandyci", row: "siege", abilities: ["tight_bond"], isHero: false, baseId: "straznik_kruka" },
    { id: "Dexter", name: "Dexter", type: "Unit", power: 10, faction: "Bandyci", row: "ranged", isHero: true },
    { id: "Bloodwyn", name: "Bloodwyn", type: "Unit", power: 10, faction: "Bandyci", row: "melee", isHero: true },
    { id: "Kruk", name: "Kruk", type: "Unit", power: 10, faction: "Bandyci", row: "melee", isHero: true },
    { id: "Thorus", name: "Thorus", type: "Unit", power: 10, faction: "Bandyci", row: "melee", isHero: true },
    { id: "Quentin", name: "Quentin", type: "Unit", power: 0, faction: "Bandyci", row: "melee", isHero: false, isToken: true },
    { id: "Wloczega", name: "Włóczęga", type: "Unit", power: 4, faction: "Bandyci", row: "melee", isHero: false },
    { id: "Straznik_niewolnikow", name: "Strażnik niewolników", type: "Unit", power: 4, faction: "Bandyci", row: "melee", isHero: false },
];
